# Generated by Django 2.1.5 on 2019-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190130_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=790000000, verbose_name='Телефон'),
        ),
    ]
