# Generated by Django 2.1.5 on 2019-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая сумма'),
        ),
    ]
