# Generated by Django 2.1.5 on 2019-01-30 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190123_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 7, 21, 14, 79438, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
