# Generated by Django 2.1.5 on 2019-01-30 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190123_2126'),
        ('shop', '0008_auto_20190130_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Photo', verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 13, 38, 27, 539528, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
